
export const chatsTypes = {
    CHATS_LOADED: 'CHATS_LOADED',
    CHANGE_ACTIONS: 'CHANGE_ACTIONS',
    HANDLE_VISIBLE_CHAT: 'HANDLE_VISIBLE_CHAT',
    PLAY_BUTTON_CLICK: 'PLAY_BUTTON_CLICK'
};

export const builderType = {
    ITEM_ADD: 'ITEM_ADD',
    ITEM_DELETE: 'ITEM_DELETE',
    ITEMS_SORT: 'ITEMS_SORT',
    ITEM_CHANGE_TYPE: 'ITEM_CHANGE_TYPE',
    ITEM_TEXT_CHANGED: 'ITEM_TEXT_CHANGED',
    ITEM_SAVE_IMAGE: 'ITEM_SAVE_IMAGE',
    CHAT_PLAY: 'CHAT_PLAY',
    ITEM_SET_NEXT_ITEM: 'ITEM_SET_NEXT_ITEM',
    CHAT_SAVE_TO_CLIPBOARD: 'CHAT_SAVE_TO_CLIPBOARD',
    CHAT_RESET: 'CHAT_RESET',
    CHAT_UPLOAD_FROM_FILE: 'CHAT_UPLOAD_FROM_FILE',
    ALERT_CHANGE_STATE: 'ALERT_CHANGE_STATE',
    SET_FOCUSED_LINE: 'SET_FOCUSED_LINE',
    CHAT_CHECK_SPECIAL_LINES: 'CHAT_CHECK_SPECIAL_LINES',
    WRONG_LINES_CHANGE_STATE: 'WRONG_LINES_CHANGE_STATE'
}
