version: "3.7"

services:
  db:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - backups_data:/var/backups/
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./entrypoint.prod.sh
    environment:
      - DB_HOST=db
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    env_file:
      - .env

  nginx:
    image: registry.teamvoy.com/mein-object/python-backend/nginx:latest
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  backups_data:
    driver_opts:
      type: none
      device: /var/backups/
      o: bind
