version: '3'
services:
  python:
    image: 081960884429.dkr.ecr.eu-central-1.amazonaws.com/${ENVIRONMENT}_images:python_${CIRCLE_WORKFLOW_ID}
    container_name: python
    entrypoint: /app/deploy/docker/python/init.sh
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - APP_PATH=${APP_PATH}
      - AWS_ACCESS_KEY_ID=${CRD_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${CRD_AWS_SECRET_ACCESS_KEY}
