# Generated by Django 2.1.7 on 2019-03-05 13:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
            ],
            options={
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Museums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('floor_amount', models.IntegerField()),
                ('tensor_flow_model', models.CharField(blank=True, max_length=45, null=True)),
                ('tensor_flow_lables', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Museums',
            },
        ),
        migrations.CreateModel(
            name='ObjectsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], default=1)),
                ('floor', models.IntegerField()),
                ('positionx', models.DecimalField(db_column='positionX', decimal_places=8, max_digits=11)),
                ('positiony', models.DecimalField(db_column='positionY', decimal_places=8, max_digits=11)),
                ('vip', models.BooleanField(default=False)),
                ('language_style', models.CharField(choices=[('easy', 'Easy'), ('fun', 'Fun'), ('kids', 'Kids'), ('professional', 'Professional')], default='easy', max_length=45)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
                ('onboarding', models.BooleanField(default=False)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Museums')),
            ],
            options={
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category_score', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exit_position', django.contrib.postgres.fields.jsonb.JSONField()),
                ('likes_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('chat_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('predifined_objects', django.contrib.postgres.fields.jsonb.JSONField()),
                ('priority_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('distance_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('predifined_collections', django.contrib.postgres.fields.jsonb.JSONField()),
                ('languages', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('device_id', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('positionx', models.DecimalField(db_column='positionX', decimal_places=8, max_digits=11)),
                ('positiony', models.DecimalField(db_column='positionY', decimal_places=8, max_digits=11)),
                ('floor', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='museums',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Settings'),
        ),
        migrations.AddField(
            model_name='collections',
            name='object_items',
            field=models.ManyToManyField(blank=True, null=True, to='main.ObjectsItem'),
        ),
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
