# Generated by Django 2.1.7 on 2019-03-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='object_items',
            new_name='objects_item',
        ),
    ]
