# Generated by Django 2.1.7 on 2019-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190305_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='user',
        ),
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ManyToManyField(to='main.Users'),
        ),
    ]
