# Generated by Django 2.1.7 on 2019-03-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190305_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='user',
        ),
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
