# Generated by Django 2.1.7 on 2019-03-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190307_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectscategories',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='objectscategories',
            old_name='object_id',
            new_name='objects_item',
        ),
    ]
