# Generated by Django 2.1.7 on 2019-03-09 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190309_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLanguageStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_style', models.CharField(blank=True, choices=[('easy', 'Easy'), ('fun', 'Fun'), ('kids', 'Kids'), ('professional', 'Professional')], max_length=45, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Votings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objects_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ObjectsItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Users')),
            ],
        ),
        migrations.AddField(
            model_name='objectslocalizations',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='objectslocalizations',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='objectslocalizations',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectslocalizations',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='language_style',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('fun', 'Fun'), ('kids', 'Kids'), ('professional', 'Professional')], max_length=45, null=True),
        ),
    ]
