# Generated by Django 2.1.7 on 2019-03-12 14:20

from django.db import migrations, models
import django.utils.timezone
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190309_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedAvatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settings', models.ManyToManyField(to='main.Settings')),
            ],
            options={
                'verbose_name_plural': 'PredefinedAvatars',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='category',
            field=models.ManyToManyField(to='main.Categories'),
        ),
    ]
