# Generated by Django 2.1.7 on 2019-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190314_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieslocalizations',
            name='language',
            field=models.CharField(choices=[(1, 'English'), (2, 'German')], default=1, max_length=45),
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='language',
            field=models.CharField(choices=[(1, 'English'), (2, 'German')], default=1, max_length=45),
        ),
    ]
