# Generated by Django 2.1.7 on 2019-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190314_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectslocalizations',
            name='language_style',
        ),
        migrations.AddField(
            model_name='objectslocalizations',
            name='object_kind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='categorieslocalizations',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('de', 'German')], default='eng', max_length=45),
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('de', 'German')], default='eng', max_length=45),
        ),
    ]
