# Generated by Django 2.1.7 on 2019-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190320_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectscategories',
            name='category',
            field=models.ManyToManyField(to='main.Categories'),
        ),
    ]
