# Generated by Django 2.1.7 on 2019-03-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190320_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
