# Generated by Django 2.1.7 on 2019-03-21 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190321_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPredefinedObjectsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('predefined_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='predefined_categories',
            field=models.ManyToManyField(to='main.Categories'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='name',
            field=models.CharField(default='Humboldt Museum', max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='settingspredefinedobjectsitems',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Settings'),
        ),
    ]
