# Generated by Django 2.1.7 on 2019-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_objectsmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumsimages',
            name='image_type',
            field=models.CharField(choices=[('smpl', 'Simple'), ('pnt', 'Pointer'), ('1_map', 'First floor map'), ('2_map', 'Second floor map'), ('3_map', 'Third floor map')], default='smpl', max_length=45),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='positionx',
            field=models.DecimalField(db_column='positionX', decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='positiony',
            field=models.DecimalField(db_column='positionY', decimal_places=0, max_digits=3),
        ),
    ]
