# Generated by Django 2.1.7 on 2019-04-04 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20190404_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslanguagestyles',
            name='language_style',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, max_length=145, null=True),
        ),
    ]
