# Generated by Django 2.1.7 on 2019-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20190404_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='device_id',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
