# Generated by Django 2.1.7 on 2019-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20190613_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumlocalization',
            name='title',
            field=models.CharField(default='Humboldt Museum', max_length=45),
        ),
    ]
