# Generated by Django 2.1.7 on 2019-09-23 10:52

from django.db import migrations
from main.models import ObjectsItem

def str_to_null(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_objectsitem_in_tensor_model'),
    ]

    operations = [
        migrations.RunPython(str_to_null)

    ]
