# Generated by Django 2.1.7 on 2020-02-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_suggestedobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestedobject',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='suggestedobject',
            name='objectsitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sug_objectsitem', to='main.ObjectsItem'),
        ),
    ]
