# Generated by Django 2.1.7 on 2020-02-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_auto_20200225_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsmap',
            name='objects_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_map', to='main.ObjectsItem'),
        ),
        migrations.AlterField(
            model_name='suggestedobject',
            name='suggested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_to_suggest', to='main.ObjectsItem'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestedobject',
            unique_together={('objectsitem', 'suggested')},
        ),
    ]
