# Generated by Django 2.1.7 on 2020-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_auto_20200226_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedobject',
            name='suggested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_to_suggest', to='main.ObjectsItem'),
        ),
    ]
