# Generated by Django 2.1.7 on 2020-03-25 12:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20200323_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsimages',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=main.models.get_image_path),
        ),
    ]
