# Generated by Django 2.1.7 on 2020-03-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_auto_20200325_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectslocalizations',
            unique_together={('objects_item', 'language')},
        ),
    ]
