# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #vagrant plugin install vagrant-env
  config.env.enable
  config.vm.define "server" do |machine|
    machine.vm.network "private_network", ip: "10.2.2.25"
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.verbose = 'vv'
      ansible.extra_vars = {
        gitlab_user: ENV["REGISTRY_USER"],
        gitlab_token: ENV["REGISTRY_TOKEN"],
        compose_file: ENV["COMPOSE_FILE"]
      }
    end
  end
end
