# Generated by Django 2.1.7 on 2019-03-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190305_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museums',
            name='setting',
        ),
        migrations.AddField(
            model_name='museums',
            name='settings',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Settings'),
        ),
    ]
