# Generated by Django 2.1.7 on 2019-03-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190307_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Settings'),
        ),
    ]
