# Generated by Django 2.1.7 on 2019-03-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190307_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Settings'),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Museums'),
        ),
    ]
