# Generated by Django 2.1.7 on 2019-03-07 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_categories_categorieslocalizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Categories')),
                ('object_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem')),
            ],
        ),
        migrations.AlterField(
            model_name='collections',
            name='objects_item',
            field=models.ManyToManyField(to='main.ObjectsItem'),
        ),
    ]
