# Generated by Django 2.1.7 on 2019-03-15 13:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190314_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumsimages',
            options={'verbose_name_plural': 'Museums Images'},
        ),
        migrations.AlterModelOptions(
            name='objectsimages',
            options={'verbose_name_plural': 'Objects Images'},
        ),
        migrations.AlterModelOptions(
            name='objectslocalizations',
            options={'verbose_name_plural': 'Objects Localizations'},
        ),
        migrations.AlterModelOptions(
            name='userslanguagestyles',
            options={'verbose_name_plural': 'Users Language Styles'},
        ),
        migrations.AlterModelOptions(
            name='votings',
            options={'verbose_name_plural': 'Votings'},
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='conversation',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path),
        ),
    ]
