# Generated by Django 2.1.7 on 2019-03-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190315_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieslocalizations',
            options={'verbose_name_plural': 'Categories Localizations'},
        ),
        migrations.AlterModelOptions(
            name='objectscategories',
            options={'verbose_name_plural': 'Objects Categories'},
        ),
        migrations.AlterModelOptions(
            name='predefinedavatars',
            options={'verbose_name_plural': 'Predefined Avatars'},
        ),
    ]
