# Generated by Django 2.1.7 on 2019-03-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190317_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedavatars',
            name='settings',
        ),
        migrations.AddField(
            model_name='predefinedavatars',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Settings'),
        ),
    ]
