# Generated by Django 2.1.7 on 2019-03-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190318_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieslocalizations',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45),
        ),
        migrations.AlterField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45),
        ),
    ]
