# Generated by Django 2.1.7 on 2019-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190320_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectslocalizations',
            name='phrase',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='positionx',
            field=models.DecimalField(db_column='positionX', decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='positiony',
            field=models.DecimalField(db_column='positionY', decimal_places=8, max_digits=11),
        ),
    ]
