# Generated by Django 2.1.7 on 2019-03-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190320_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ObjectsItem'),
        ),
    ]
