# Generated by Django 2.1.7 on 2019-03-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190321_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem'),
        ),
    ]
