# Generated by Django 2.1.7 on 2019-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190321_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45),
        ),
    ]
