# Generated by Django 2.1.7 on 2019-03-21 17:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190321_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('de', 'German')], max_length=3),
        ),
    ]
