# Generated by Django 2.1.7 on 2019-03-22 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190322_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='position_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='settings',
            name='category_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='priority_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
