# Generated by Django 2.1.7 on 2019-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190322_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsimages',
            name='image_type',
            field=models.CharField(choices=[('smpl', 'Simple'), ('map', 'mMp')], default='map', max_length=45),
        ),
    ]
