# Generated by Django 2.1.7 on 2019-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_objectsimages_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectsimages',
            name='image_type',
        ),
        migrations.AlterField(
            model_name='museumsimages',
            name='image_type',
            field=models.CharField(choices=[('smpl', 'Simple'), ('1_map', 'First floor map'), ('2_map', 'Second floor map'), ('3_map', 'Third floor map')], default='smpl', max_length=45),
        ),
    ]
