# Generated by Django 2.1.7 on 2019-03-26 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20190326_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_map', models.ImageField(upload_to='')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objects_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem')),
            ],
            options={
                'verbose_name_plural': 'Objects Map',
            },
        ),
    ]
