# Generated by Django 2.1.7 on 2019-03-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20190326_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsmap',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem'),
        ),
    ]
