# Generated by Django 2.1.7 on 2019-03-27 13:05

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20190326_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumsimages',
            name='image',
            field=models.ImageField(max_length=110, upload_to=main.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='objectsmap',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objectsmap', to='main.ObjectsItem'),
        ),
    ]
