# Generated by Django 2.1.7 on 2019-03-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20190327_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='objectsmap',
            name='objects_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object_map', to='main.ObjectsItem'),
        ),
    ]
