# Generated by Django 2.1.7 on 2019-03-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20190328_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='objects_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem'),
        ),
    ]
