# Generated by Django 2.1.7 on 2019-04-02 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20190401_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='device_id',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='positionx',
            field=models.DecimalField(blank=True, db_column='positionX', decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='positiony',
            field=models.DecimalField(blank=True, db_column='positionY', decimal_places=8, max_digits=11, null=True),
        ),
    ]
