# Generated by Django 2.1.7 on 2019-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20190403_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
