# Generated by Django 2.1.7 on 2019-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20190403_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_lables',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_model',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to=''),
        ),
    ]
