# Generated by Django 2.1.7 on 2019-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20190403_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_lables',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='', verbose_name='/tensor_label/'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_model',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='', verbose_name='/tensor_model/'),
        ),
    ]
