# Generated by Django 2.1.7 on 2019-04-04 07:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20190403_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_lables',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_label/'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='tensor_flow_model',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_model/'),
        ),
        migrations.AlterField(
            model_name='userslanguagestyles',
            name='language_style',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
