# Generated by Django 2.1.7 on 2019-04-04 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20190404_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusemsTensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensor_flow_model', models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_model/')),
                ('tensor_flow_lables', models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_label/')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Tensor flow models',
            },
        ),
        migrations.RemoveField(
            model_name='museums',
            name='tensor_flow_lables',
        ),
        migrations.RemoveField(
            model_name='museums',
            name='tensor_flow_model',
        ),
        migrations.AddField(
            model_name='musemstensor',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Museums'),
        ),
    ]
