# Generated by Django 2.1.7 on 2019-04-04 13:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20190404_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_item', models.UUIDField(blank=True, null=True)),
                ('category', models.UUIDField(blank=True, null=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Deleted Items',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='language_styles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('easy', 'Easy'), ('fun', 'Fun'), ('kids', 'Kids'), ('professional', 'Professional')], max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='musemstensor',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='museumtensor', to='main.Museums'),
        ),
    ]
