# Generated by Django 2.1.7 on 2019-04-04 13:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20190404_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='language_styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('easy', 'Easy'), ('fun', 'Fun'), ('kids', 'Kids'), ('professional', 'Professional')], max_length=80),
        ),
    ]
