# Generated by Django 2.1.7 on 2019-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20190404_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsitem',
            name='positionx',
            field=models.DecimalField(db_column='positionX', decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='positiony',
            field=models.DecimalField(db_column='positionY', decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='users',
            name='positionx',
            field=models.DecimalField(db_column='positionX', decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='users',
            name='positiony',
            field=models.DecimalField(db_column='positionY', decimal_places=0, default=0, max_digits=4),
        ),
    ]
