# Generated by Django 2.1.7 on 2019-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20190419_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsimages',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
