# Generated by Django 2.1.7 on 2019-05-23 16:14

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_museums_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('museum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Museums')),
            ],
        ),
        migrations.AlterField(
            model_name='museumsimages',
            name='image_type',
            field=models.CharField(choices=[('smpl', 'Simple'), ('logo', 'Logo'), ('pnt', 'Pointer'), ('1_map', 'First floor map'), ('2_map', 'Second floor map'), ('3_map', 'Third floor map')], default='smpl', max_length=45),
        ),
    ]
