# Generated by Django 2.1.7 on 2019-05-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20190523_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticRelationLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('objects_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ObjectsItem')),
            ],
        ),
    ]
