# Generated by Django 2.1.7 on 2019-05-24 10:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20190523_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openningtime',
            name='weekday',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('suturday', 'Saturday'), ('sunday', 'Sunday')], max_length=110),
        ),
    ]
