# Generated by Django 2.1.7 on 2019-05-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_semanticrelationlocalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semanticrelation',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='semanticrelation',
            name='description_en',
        ),
        migrations.AlterField(
            model_name='semanticrelationlocalization',
            name='objects_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SemanticRelation'),
        ),
    ]
