# Generated by Django 2.1.7 on 2019-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20190524_0917'),
        ('main', '0073_museums_location'),
    ]

    operations = [
    ]
