# Generated by Django 2.1.7 on 2019-05-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20190524_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='museums',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
