# Generated by Django 2.1.7 on 2019-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_museums_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='image',
            field=models.ImageField(max_length=110, upload_to=''),
        ),
    ]
