# Generated by Django 2.1.7 on 2019-05-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_merge_20190524_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumsimages',
            name='image_type',
            field=models.CharField(choices=[('smpl', 'Simple'), ('logo', 'Logo'), ('pnt', 'Pointer'), ('1_map', 'First floor map'), ('2_map', 'Second floor map'), ('3_map', 'Third floor map')], default='smpl', max_length=45),
        ),
        migrations.AlterField(
            model_name='semanticrelationlocalization',
            name='objects_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', related_query_name='localizations', to='main.SemanticRelation'),
        ),
    ]
