# Generated by Django 2.1.7 on 2019-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20190529_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='musemstensor',
            name='mobile_tensor_flow_lables',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_label/'),
        ),
        migrations.AddField(
            model_name='musemstensor',
            name='mobile_tensor_flow_model',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to='tensor_model/'),
        ),
    ]
