# Generated by Django 2.1.7 on 2019-05-29 14:48

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20190529_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('suturday', 'Saturday'), ('sunday', 'Sunday')], max_length=110)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='museums',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='image',
            field=models.ImageField(max_length=110, upload_to=''),
        ),
        migrations.AddField(
            model_name='openningtime',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Museums'),
        ),
    ]
