# Generated by Django 2.1.7 on 2019-05-30 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20190529_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticrelationlocalization',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
