# Generated by Django 2.1.7 on 2019-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20190530_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='museums',
            name='ratio_pixel_meter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
