# Generated by Django 2.1.7 on 2019-06-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_museums_ratio_pixel_meter'),
        ('main', '0079_auto_20190603_0714'),
    ]

    operations = [
    ]
