# Generated by Django 2.1.7 on 2019-06-04 07:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_museums_ratio_pixel_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsitem',
            name='cropped_avatar',
            field=models.ImageField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path),
        ),
    ]
