# Generated by Django 2.1.7 on 2019-06-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_objectsitem_cropped_avatar'),
        ('main', '0084_merge_20190603_0746'),
    ]

    operations = [
    ]
