# Generated by Django 2.1.7 on 2019-06-13 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_merge_20190604_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45)),
                ('title', models.CharField(default='Humboldt Museum', max_length=45, unique=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='museums',
            name='name',
        ),
        migrations.RemoveField(
            model_name='museums',
            name='specialization',
        ),
        migrations.AddField(
            model_name='categorieslocalizations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='museumlocalization',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', related_query_name='localizations', to='main.Museums'),
        ),
    ]
