# Generated by Django 2.1.7 on 2019-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20190614_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='recognition_threshold',
            field=models.SmallIntegerField(default=50),
        ),
    ]
