# Generated by Django 2.1.7 on 2019-07-12 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_chats_planned'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', related_query_name='tours', to='main.Museums')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumTourLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=45)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', related_query_name='localizations', to='main.MuseumTour')),
            ],
        ),
        migrations.CreateModel(
            name='TourObjectsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourobjects', related_query_name='tourobjects', to='main.MuseumTour')),
                ('tour_object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tourobjects', related_query_name='tourobjects', to='main.ObjectsItem')),
            ],
        ),
    ]
