# Generated by Django 2.1.7 on 2019-07-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_settings_recognition_threshold'),
        ('main', '0089_museumtour_museumtourlocalization_tourobjectsitems'),
    ]

    operations = [
    ]
