# Generated by Django 2.1.7 on 2019-08-05 14:20

from django.db import migrations, models
import django.db.models.deletion
import main.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20190805_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstensorimage',
            name='image',
            field=models.ImageField(max_length=110, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='mein-objekt-tensorflow'), upload_to=main.models.get_tensor_image_path),
        ),
        migrations.AlterField(
            model_name='objectstensorimage',
            name='objects_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_tensor_image', to='main.ObjectsItem'),
        ),
    ]
