# Generated by Django 2.1.7 on 2019-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20190805_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectstensorimage',
            options={'verbose_name_plural': 'Objects Tensor Images'},
        ),
        migrations.AddField(
            model_name='musemstensor',
            name='mobile_tensor_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('validating', 'Validating')], default='ready', max_length=45),
        ),
        migrations.AddField(
            model_name='musemstensor',
            name='tensor_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('validating', 'Validating')], default='ready', max_length=45),
        ),
    ]
