# Generated by Django 2.1.7 on 2019-08-13 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20190806_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('museum_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tour', related_query_name='user_tour', to='main.MuseumTour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Users')),
            ],
        ),
        migrations.AlterField(
            model_name='musemstensor',
            name='mobile_tensor_status',
            field=models.CharField(choices=[('none', 'None'), ('ready', 'Ready!'), ('processing', 'processing...'), ('validating', 'validating...')], default='none', max_length=45),
        ),
        migrations.AlterField(
            model_name='musemstensor',
            name='tensor_status',
            field=models.CharField(choices=[('none', 'None'), ('ready', 'Ready!'), ('processing', 'processing...'), ('validating', 'validating...')], default='none', max_length=45),
        ),
    ]
