# Generated by Django 2.1.7 on 2019-09-05 09:38

import django.core.validators
from django.db import migrations, models
import main.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20190821_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musemstensor',
            name='mobile_tensor_status',
            field=models.CharField(choices=[('none', 'None'), ('ready', 'Ready!'), ('processing', 'processing...'), ('validating', 'validating...'), ('error', 'Model creation error, please add more objects with tensor images')], default='none', max_length=145),
        ),
        migrations.AlterField(
            model_name='musemstensor',
            name='tensor_status',
            field=models.CharField(choices=[('none', 'None'), ('ready', 'Ready!'), ('processing', 'processing...'), ('validating', 'validating...'), ('error', 'Model creation error, please add more objects with tensor images')], default='none', max_length=145),
        ),
        migrations.AlterField(
            model_name='objectslocalizations',
            name='conversation',
            field=models.FileField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AlterField(
            model_name='objectstensorimage',
            name='image',
            field=models.ImageField(max_length=110, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='mein-objekt-tensorflow'), upload_to=main.models.get_tensor_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'JPEG'])]),
        ),
    ]
