# Generated by Django 2.1.7 on 2019-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20190905_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='save_collections_to_tensor',
            field=models.BooleanField(default=False),
        ),
    ]
