# Generated by Django 2.1.7 on 2019-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_settings_save_collections_to_tensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsitem',
            name='author',
            field=models.CharField(choices=[('none', 'None'), ('ready', 'Ready!'), ('processing', 'processing...'), ('validating', 'validating...'), ('error', 'Model creation error, please add more objects with tensor images')], default='none', max_length=145),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
