# Generated by Django 2.1.7 on 2019-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20190915_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsitem',
            name='in_tensor_model',
            field=models.BooleanField(default=False),
        ),
    ]
