# Generated by Django 2.1.7 on 2019-11-13 15:50

import django.core.validators
from django.db import migrations, models
import main.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20190923_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstensorimage',
            name='image',
            field=models.ImageField(max_length=110, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='mein-objekt-tensorflow'), upload_to=main.models.get_tensor_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'JPG', 'JPEG'])]),
        ),
    ]
