# Generated by Django 2.1.7 on 2020-02-20 09:44

from django.db import migrations, models
from main.models import ObjectsItem, Users

def lvl_to_null(apps, schema_editor):
    for (i, j) in zip(ObjectsItem.objects.all(), Users.objects.all()):
        i.object_level, j.user_level = 0, 0
        i.save()
        j.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20200219_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsitem',
            name='object_level',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], default=0, max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_level',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], default=0, max_length=45),
        ),
        migrations.RunPython(lvl_to_null)
    ]

