# Generated by Django 2.1.7 on 2020-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20200217_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='font_size',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
