# Generated by Django 2.1.7 on 2020-02-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_auto_20200224_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedobject',
            name='suggested',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_to_suggest', to='main.ObjectsItem'),
        ),
    ]
