# Generated by Django 2.1.7 on 2020-02-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_suggestedobject_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedobject',
            name='suggested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_to_suggest', to='main.ObjectsItem'),
        ),
    ]
