# Generated by Django 2.1.7 on 2020-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_auto_20200227_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='redirection_timout',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
