# Generated by Django 2.1.7 on 2020-03-13 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20200306_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleLine',
        ),
        migrations.DeleteModel(
            name='SingleLineLocalization',
        ),
    ]
