# Generated by Django 2.1.7 on 2020-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_auto_20200316_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleline',
            name='redirect',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
