# Generated by Django 2.1.7 on 2020-03-20 11:52

from django.db import migrations, models
import main.models
from main.models import ObjectsItem, Users


def lvl_to_on2(apps, schema_editor):
    for (i, j) in zip(ObjectsItem.objects.all(), Users.objects.all()):
        i.object_level, j.user_level = 1, 1
        i.save()
        j.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_auto_20200317_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsitem',
            name='avatar',
            field=models.ImageField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path, verbose_name='full_image'),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='cropped_avatar',
            field=models.ImageField(blank=True, max_length=110, null=True, upload_to=main.models.get_image_path, verbose_name='detail_image'),
        ),
        migrations.AlterField(
            model_name='objectsitem',
            name='object_level',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=45),
        ),
        migrations.AlterField(
            model_name='singleline',
            name='line_type',
            field=models.CharField(choices=[('redirect', 'Redirect'), ('multichoice', 'Multichoice'), ('exit', 'Exit'), ('cam', 'Cam'), ('map', 'Map'), ('collection', 'Collection'), ('image1', 'Image 1'), ('image2', 'Image 2'), ('image3', 'Image 3')], default='redirect', max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_level',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=45),
        ),
        migrations.RunPython(lvl_to_on2)
    ]
