# Generated by Django 2.1.7 on 2020-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_singleline_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdesigner',
            old_name='poll',
            new_name='active',
        ),
    ]
