# Generated by Django 2.1.7 on 2020-03-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_auto_20200325_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieslocalizations',
            options={'verbose_name_plural': 'Category Localizations'},
        ),
        migrations.AlterModelOptions(
            name='museumlocalization',
            options={'verbose_name_plural': 'Museum Localizations'},
        ),
        migrations.AlterModelOptions(
            name='museumtourlocalization',
            options={'verbose_name_plural': 'Tour Localizations'},
        ),
        migrations.AlterModelOptions(
            name='objectslocalizations',
            options={'verbose_name_plural': 'Object Localizations'},
        ),
        migrations.AlterModelOptions(
            name='semanticrelationlocalization',
            options={'verbose_name_plural': 'Semantil relation Localizations'},
        ),
        migrations.AlterModelOptions(
            name='singlelinelocalization',
            options={'verbose_name_plural': 'Line Localizations'},
        ),
        migrations.RenameField(
            model_name='semanticrelationlocalization',
            old_name='objects_item',
            new_name='relation',
        ),
        migrations.AlterUniqueTogether(
            name='categorieslocalizations',
            unique_together={('category', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='museumlocalization',
            unique_together={('museum', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='museumtourlocalization',
            unique_together={('tour', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='semanticrelationlocalization',
            unique_together={('relation', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='singlelinelocalization',
            unique_together={('line', 'language')},
        ),
    ]
